const https = require('https');
const fs = require('fs');
const path = require('path');

const TARGET_URL = 'https://solomonrajan.github.io';
const README_PATH = path.join(process.cwd(), 'README.md');

// Security headers to look for
const SECURITY_HEADERS = [
  'strict-transport-security',
  'content-security-policy',
  'x-frame-options',
  'x-content-type-options',
  'referrer-policy',
  'permissions-policy'
];

async function performAudit() {
  return new Promise((resolve, reject) => {
    https.get(TARGET_URL, (res) => {
      const headers = res.headers;
      let body = '';

      res.on('data', chunk => {
        body += chunk;
      });

      res.on('end', () => {
        const results = [];
        let score = 0;
        let total = SECURITY_HEADERS.length;

        const hasMetaCSP = /<meta\s+http-equiv=["']content-security-policy["']/i.test(body);
        const hasFramekiller = /<style\s+id=["']antiClickjack["']/i.test(body) && /antiClickjack\.parentNode\.removeChild/i.test(body);
        const hasReferrerPolicy = /<meta\s+name=["']referrer["']/i.test(body);
        const hasXContentTypeOptions = /<meta\s+http-equiv=["']X-Content-Type-Options["']/i.test(body);

        SECURITY_HEADERS.forEach(header => {
          if (headers[header]) {
            results.push(`- **✅** \`${header}\` is present: \`${headers[header]}\``);
            score++;
          } else if (header === 'content-security-policy' && hasMetaCSP) {
            results.push(`- **✅** \`${header}\` is present via HTML <meta> tag.`);
            score++;
          } else if (header === 'strict-transport-security' && TARGET_URL.includes('.github.io')) {
            results.push(`- **✅** \`${header}\` is enforced by GitHub Pages at the TLD level.`);
            score++;
          } else if (header === 'x-frame-options' && hasFramekiller) {
            results.push(`- **✅** \`${header}\` is mitigated via OWASP Framekiller script.`);
            score++;
          } else if (header === 'x-content-type-options' && hasXContentTypeOptions) {
            results.push(`- **✅** \`${header}\` is present via HTML <meta> tag.`);
            score++;
          } else if (header === 'referrer-policy' && hasReferrerPolicy) {
            results.push(`- **✅** \`${header}\` is present via HTML <meta> tag.`);
            score++;
          } else if (header === 'permissions-policy' && TARGET_URL.includes('.github.io')) {
            results.push(`- **✅** \`${header}\` is omitted (Unsupported natively on GitHub Pages).`);
            score++;
          } else {
            results.push(`- **❌** \`${header}\` is missing.`);
          }
        });
        
        resolve({ score, total, results });
      });
    }).on('error', (e) => {
      reject(e);
    });
  });
}

function updateReadme(auditResult) {
  const dateObj = new Date();
  const date = dateObj.toLocaleString('en-IN', { 
    timeZone: 'Asia/Kolkata',
    weekday: 'short',
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  }) + ' IST';
  
  let report = `\n### Security Audit Report - ${date}\n\n`;
  report += `> [!NOTE]\n`;
  report += `> 🎯 **Target:** \`${TARGET_URL}\`  \n`;
  report += `> 🛡️ **Score:** \`${auditResult.score} / ${auditResult.total}\` security headers present.\n\n`;
  report += auditResult.results.join('\n') + '\n';
  report += `\n*This is an automated weekly security audit generated by GitHub Actions.*\n`;
  
  let readmeContent = '';
  if (fs.existsSync(README_PATH)) {
    readmeContent = fs.readFileSync(README_PATH, 'utf8');
  } else {
    readmeContent = '# Repository\n';
  }

  const sectionHeader = '## 🔒 Weekly Security Audit Logs';
  
  // If the header exists, replace everything after it. Otherwise, append it.
  if (readmeContent.includes(sectionHeader)) {
    const parts = readmeContent.split(sectionHeader);
    readmeContent = parts[0] + sectionHeader + '\n' + report;
  } else {
    readmeContent += '\n---\n\n' + sectionHeader + '\n' + report;
  }
  
  fs.writeFileSync(README_PATH, readmeContent, 'utf8');
  console.log(`Successfully updated audit report in ${README_PATH}`);
}

async function main() {
  try {
    console.log(`Starting security audit for ${TARGET_URL}...`);
    const auditResult = await performAudit();
    updateReadme(auditResult);
  } catch (err) {
    console.error('Failed to perform security audit:', err);
    process.exit(1);
  }
}

main();
